### 2.2 Numpy 배열(ndarray)

In [3]:
import cv2
img = cv2.imread('images/read_color.jpg')
print(type(img))

<class 'numpy.ndarray'>


In [5]:
img

array([[[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       ...,

       [[ 51,  64,  56],
        [ 51,  64,  56],
        [ 42,  55,  47],
        ...,
        [145, 149, 150],
        [162, 166, 167],
        [161, 165, 166]],

       [[ 31,  50,  41],
        [ 35,  56,  47],
        [ 28,  53,  43],
        ...,
        [152, 155, 159],
        [163, 166, 170],
        [155, 158, 162]],

       [[ 22,  46,  36],
        [ 16,  43,  33],
        [ 19,  51,  40],
        ...,
        [151, 154, 159],
        [147, 150, 155],
        [157, 160, 165]]

In [4]:
print(img.ndim) #차원의 수
print(img.shape) # 각 차원의 크기(튜플) = 픽셀의 개수 (300 * 400, RGB)
print(img.size) # 전체 이미지의 크기(bytes)
print(img.dtype) # 요소의 데이터 타입
print(img.itemsize) # 각 요소의 바이트 크기

3
(300, 400, 3)
360000
uint8
1


### 2.3 Numpy 객체 만들기

In [7]:
import numpy as np # Numpy를 사용할 때 통상적으로 이렇게 np로 줄여서 사용한다.
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [8]:
a.dtype

dtype('int64')

In [9]:
a = np.array([1, 2, 3.14, 4]) # 하나라도 실수가 있다면 실수 배열 생성
a

array([1.  , 2.  , 3.14, 4.  ])

In [10]:
a.dtype

dtype('float64')

In [11]:
a.shape # 1행4열 - 일차원 배열의 차원은 ,가 붙어서 출력

(4,)

In [12]:
b = np.array([[1,2,3,4],[5,6,7,8]])
b

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
b.shape # 2행4열

(2, 4)

In [14]:
c = np.array([[1],[2],[3],[4]])
c

array([[1],
       [2],
       [3],
       [4]])

In [15]:
c.shape # 4행1열

(4, 1)

In [16]:
d = np.array([[1, 2, 3, 4]])
d

array([[1, 2, 3, 4]])

In [17]:
d.T # 전치행렬

array([[1],
       [2],
       [3],
       [4]])

In [18]:
a = np.empty((2,3)) # 환경에 따라서 0으로 채워지기도 하지만, prompt 상에서 실행
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
a.dtype

dtype('float64')

In [20]:
a.fill(255) # 주어진 값으로 채우지만, 원래 a가 float64이므로 실수형으로 채워짐. 
a

array([[255., 255., 255.],
       [255., 255., 255.]])

In [21]:
b = np.zeros((2,3)) # 실수로 생성되기 때문에 dtype 지정 필요
b

array([[0., 0., 0.],
       [0., 0., 0.]])

In [22]:
c = np.zeros((2,3), dtype=np.uint8) # 이미지의 픽셀은 정수값을 사용하므로 8비트
c

array([[0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [23]:
d = np.ones((2,3), dtype=np.int16)
d # 픽셀이 6개 (1로 구성)

array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [24]:
e = np.full((2,4,3), 255, dtype=np.uint8) # 컬러 이미지는 하나의 픽셀이 RGB값
e # 픽셀이 8개 ([255, 255, 255]로 구성)

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [48]:
import cv2
img = cv2.imread('images/read_color.jpg')
img

array([[[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       [[187, 132,  87],
        [187, 132,  87],
        [187, 132,  87],
        ...,
        [161,  94,  55],
        [161,  94,  55],
        [161,  94,  55]],

       ...,

       [[ 51,  64,  56],
        [ 51,  64,  56],
        [ 42,  55,  47],
        ...,
        [145, 149, 150],
        [162, 166, 167],
        [161, 165, 166]],

       [[ 31,  50,  41],
        [ 35,  56,  47],
        [ 28,  53,  43],
        ...,
        [152, 155, 159],
        [163, 166, 170],
        [155, 158, 162]],

       [[ 22,  46,  36],
        [ 16,  43,  33],
        [ 19,  51,  40],
        ...,
        [151, 154, 159],
        [147, 150, 155],
        [157, 160, 165]]

In [108]:
a = np.empty_like(img) # 배열의 크기만 같고 내용은 무작위 값으로 들어간다.
a 

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(300, 400, 3), dtype=uint8)

In [56]:
b = np.zeros_like(img)
b

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       ...,

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        ...,
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], shape=(300, 400, 3), dtype=uint8)

In [28]:
print(img.shape)
print(a.shape)
print(b.shape)

(300, 400, 3)
(300, 400, 3)
(300, 400, 3)


In [32]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [33]:
b = np.arange(5.0)
b

array([0., 1., 2., 3., 4.])

In [34]:
c = np.arange(3,9,2) # range가 아닌 arange로 사용 - 시작, 끝, 증분
c

array([3, 5, 7])

In [36]:
d = np.random.rand(2,3) # 0~1 사이값으로 2행3열
d

array([[0.24867284, 0.34065683, 0.17805467],
       [0.11916555, 0.02365277, 0.09920544]])

In [46]:
e = np.random.randn(2,3) # 표준정규분포(평균:0, 분산:1)를 따르는 난수로 2행3열 - 분산이 1이므로 음수값 가능
e

array([[ 0.6596356 ,  0.01474114,  0.07356135],
       [ 0.19922064, -0.13495254, -0.1614902 ]])

In [47]:
f = np.random.randint(0,256,(3,3)) # 시작, 끝, 3행3열 정수값 - 끝값은 포함되지 않는다.(256은 제외)
f

array([[ 43, 130, 228],
       [178, 255, 249],
       [183, 114,   1]])

### 2.4 배열 속성 변경

In [79]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [80]:
b = a.astype(np.float64) # 자료형의 스트링을 써도 된다. 'float64' - 새로운 메모리 할당
b

array([0., 1., 2., 3., 4.])

In [82]:
c = np.uint8(b) # dtype 함수를 사용할 수도 있다.
c

array([0, 1, 2, 3, 4], dtype=uint8)

In [83]:
a = np.arange(6) # 바꾸기 전과 후의 요소의 수가 값아야 한다.
a

array([0, 1, 2, 3, 4, 5])

In [84]:
b = a.reshape(2,3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [85]:
c = np.reshape(a, (2,3))
c

array([[0, 1, 2],
       [3, 4, 5]])

In [86]:
d = np.arange(100).reshape(2, -1) # -1을 사용하면 요소수 계산을 하지 않아도 됨. (-1은 나머지 차원에 맞춰서 넣어줌, 1번만 사용 가능)
d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47,
        48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98, 99]])

In [87]:
e = np.arange(100).reshape(-1, 5)
e

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [88]:
a = np.zeros((2,3))
a

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
b = a.reshape((6,)) # 요소의 총 개수를 세어서 입력해야 함.
b

array([0., 0., 0., 0., 0., 0.])

In [90]:
c = a.reshape(-1) # 요소의 수를 셀 필요없이 무조건 1차원으로 변경
c

array([0., 0., 0., 0., 0., 0.])

In [91]:
d = np.ravel(a) # 요소의 수를 셀 필요없음. 현재 차원에 상관없이 1차원으로 변경
d

array([0., 0., 0., 0., 0., 0.])

### 2.5 브로드캐스팅 연산

In [92]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [93]:
a + 5

array([5, 6, 7, 8, 9])

In [94]:
a ** 2

array([ 0,  1,  4,  9, 16])

In [95]:
b = np.arange(6).reshape(2,-1)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
b * 2

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [97]:
a > 2 # 비교연산도 가능 (모든 원소가 2보다 큰지 확인)

array([False, False, False,  True,  True])

In [99]:
a = np.arange(24).reshape(2,3,4)
b = np.arange(12).reshape(3,4) # (3,4) --> 2차원이 3차로 변환되어 차원1 추가 (1,3,4) --> (2,3,4) 
print(a)
print(b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [100]:
a + b

array([[[ 0,  2,  4,  6],
        [ 8, 10, 12, 14],
        [16, 18, 20, 22]],

       [[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]]])